#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
SVG Exporter - Export font glyphs to SVG format
"""

from core.ot.glyph import Glyph
from core.ot.otfont import OTFont


class SVGExporter:
    """
    Exports font glyphs to SVG format.

    SVG output includes:
    - SVG header with proper viewBox
    - Path elements for each glyph
    - Quadratic bezier curves for outlines
    """

    def __init__(self, font: OTFont):
        """
        Initialize SVGExporter.

        Args:
            font: OTFont to export
        """
        self._font = font

    def export(self, output_path: str):
        """
        Export font to SVG file.

        Args:
            output_path: Path for output SVG file
        """
        num_glyphs = self._font.get_num_glyphs()
        units_per_em = self._font.get_head_table().get_units_per_em()

        svg_content = self._generate_svg(num_glyphs, units_per_em)

        with open(output_path, 'w', encoding='utf-8') as f:
            f.write(svg_content)

    def _generate_svg(self, num_glyphs: int, units_per_em: int) -> str:
        """
        Generate SVG content.

        Args:
            num_glyphs: Number of glyphs
            units_per_em: Units per EM

        Returns:
            SVG content as string
        """
        width = units_per_em * num_glyphs
        height = units_per_em

        lines = [
            '<?xml version="1.0" encoding="UTF-8"?>',
            f'<svg xmlns="http://www.w3.org/2000/svg" '
            f'viewBox="0 0 {width} {height}" '
            f'width="{width}" height="{height}">',
            f'  <title>Exported Font</title>',
            f'  <desc>Generated by Typecast</desc>',
        ]

        for i in range(num_glyphs):
            glyph = self._font.get_glyph(i)
            if glyph:
                path_data = self._glyph_to_svg_path(glyph)
                offset_x = i * units_per_em

                lines.append(
                    f'  <g id="glyph-{i}" transform="translate({offset_x}, 0)">'
                )
                lines.append(f'    <path d="{path_data}" fill="black"/>')
                lines.append('  </g>')

        lines.append('</svg>')

        return '\n'.join(lines)

    def _glyph_to_svg_path(self, glyph: Glyph) -> str:
        """
        Convert glyph to SVG path data.

        Args:
            glyph: Glyph object

        Returns:
            SVG path data string
        """
        path_parts = []
        point_count = glyph.get_point_count()

        if point_count == 0:
            return ""

        first_index = 0
        contour_start = 0

        for i in range(point_count):
            point = glyph.get_point(i)

            if point.end_of_contour:
                contour_points = glyph.get_point_count() - 2

                if contour_start < contour_points:
                    contour_end = i - 1 if i < point_count else i
                    path_data = self._build_contour(glyph, contour_start, contour_end - contour_start + 1)
                    path_parts.append(path_data)

                contour_start = i + 1

        return ' '.join(path_parts)

    def _build_contour(self, glyph: Glyph, start_index: int, count: int) -> str:
        """
        Build path data for a single contour.

        Args:
            glyph: Glyph object
            start_index: Starting point index
            count: Number of points in contour

        Returns:
            SVG path data string
        """
        if count == 0:
            return ""

        parts = []
        offset = 0
        is_first = True

        while offset < count:
            idx_curr = start_index + (offset % count)
            idx_next = start_index + ((offset + 1) % count)
            idx_next_next = start_index + ((offset + 2) % count)

            point = glyph.get_point(idx_curr)
            point_next = glyph.get_point(idx_next)
            point_next_next = glyph.get_point(idx_next_next)

            if point.on_curve and point_next.on_curve:
                cmd = "M" if is_first else "L"
                parts.append(f"{cmd}{point.x},{-point.y}")
                parts.append(f"L{point_next.x},{-point_next.y}")
                offset += 1

            elif point.on_curve and not point_next.on_curve and point_next_next.on_curve:
                cmd = "M" if is_first else "L"
                parts.append(f"{cmd}{point.x},{-point.y}")
                parts.append(f"Q{point_next.x},{-point_next.y} {point_next_next.x},{-point_next_next.y}")
                offset += 2

            elif not point.on_curve and point_next.on_curve:
                cmd = "M" if is_first else "L"
                parts.append(f"{cmd}{point_next.x},{-point_next.y}")
                offset += 1

            else:
                if is_first:
                    parts.append(f"M{point.x},{-point.y}")

                mid_x = point.x + (point_next.x - point.x) // 2
                mid_y = point.y + (point_next.y - point.y) // 2

                parts.append(f"Q{point.x},{-point.y} {mid_x},{-mid_y}")
                offset += 1

            is_first = False

        parts.append("Z")

        return ' '.join(parts)
